name: Check
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  powershell:
    runs-on: windows-latest
    steps:
      - name: Check Windows PowerShell 5.1
        shell: powershell
        run: |
          $ErrorActionPreference = 'Stop'
          $source = Invoke-RestMethod "https://raw.githubusercontent.com/$env:GITHUB_REPOSITORY/$env:GITHUB_SHA/run.ps1"
          & ([scriptblock]::Create($source)) -SelfTest
      - name: Check PowerShell 7
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $source = Invoke-RestMethod "https://raw.githubusercontent.com/$env:GITHUB_REPOSITORY/$env:GITHUB_SHA/run.ps1"
          & ([scriptblock]::Create($source)) -SelfTest
